---
title: "Response to Reviewers"
author: ""
date: "8/23/2021"
output: pdf_document
---

We would like to express our gratitude to the editors and anonymous reviewers for their time and attention to our submission.

## Reviewer #1: 

I appreciate the authors' efforts to address my comments. There are some points that need further clarification.

\textcolor{blue}{Thank you for the opportunity to further clarify the paper.}

1. The BFCA introduces an element of congestion into accessibility calculations. You are talking about congestion at docking stations, right? If so, please specify. Also, this is a static approach without considering the time dimension. It essentially assumes that all travelers arrive at the
docking stations simultaneously, and thus one bicycle can be used only by one user. This is hardly the case in any real-world settings. How would you justify this?

\textcolor{blue}{Thank you for this comment. Floating catchment areas introduce an element of demand (or congestion). We clarified in the text that demand in our case is at the docking stations (see \emph{page}). You are right that the analysis is static in that it does not account for temporal variations in demand. Unfortunately, the number of bicycles available at each docking station at various times throughout the day is not available publicly, and we are not able to implement a dynamic analysis at the moment. We note this as a direction for future research (see \emph{page}). With respect to the static analysis, it is true that not all users arrive at a docking station at the same time. However, as a standard, this is still a valid assumption from a systems design perspective. Contrast to standards in terms of area of park per population: not everyone goes to the park at the same time, but calculating area of park per person is still a useful indicator of supply and demand. Similar standards for health care provision exist: not everyone goes to an emergency room at the same time, but calculating ER beds per person is still a good indicator of supply and demand. In the case of accessibility to public bicycle share programs, discussing the capacity of the system in these terms may be surprising initially, but we'd argue that this is because no standards have been developed for this kind of public service.}

2. In response to my previous comment 3, the authors noted that the data are not aggregated. In the abstract, they say "we then reaggregate the estimated accessibility for further analysis using census data". I am confused. I am also confused about the geographic units of analysis. Population cell is used in Section 4.1. Then in Section 4.2 population data is interpolated to smaller polygons that are 50-by-50 in size. I guess these are the same thing. Besides, there is something named micro-zones. Please check carefully throughout the manuscript and unify the terms.

\textcolor{blue}{We are sorry that this was unclear. In section 4.1, we mean population units in general; they could be census polygons, dissemination areas, interpolated populatation, or any other cartographic representation of the population. We have changed the text to say "population unit" (see \emph{page}) to ensure that this is not confused with the population cells in section 4.2. These populations cells are the 50x50m polygons that we used to interpolate the population from census dissemination areas (DAs) to smaller geographical units. For vertical equity analysis, we used census income data at the level of DAs. In figures 9-12, accessibility is seen at the level of the 50x50m population cells, and income is identical for all cells in the same DA. In other words, accessibility is still spatially disaggregated but income is from the DAs. In Table 1, we did aggregate accessibility, but this aggregation is not by geography but rather by income level. A major advantage of the BFCA approach is that this kind of aggregation is possible while still preserving the population and level of service. We have edited the abstract and section 4.1 to clarify this. We also revised the text to make consistent use of the terms.}

3. Regarding the distance threshold, I guess you used it to compute w_ij via a distance decay function. But it is not clear how the distance-decay function is defined. Further, it is counterintuitive to me that the increase in the distance threshold decreases the accessibility. 
With the increase in the distance threshold, more people can reach the docking stations. Isn't this indicating an increase in the accessibility? When the demand surpasses the capacity, the number of people that can be served is bounded by the capacity of the docking station. But it will not decrease. Adding an upper bound to Pj may resolve this issue. But this brings me to the problem of why considering congestion at the very beginning? For highway systems, we need to consider congestion since the higher the volume, the longer the queuing delay one needs to pass the highway in the congested regime. However, are customers going to wait in a bikeshare system? A clearer motivation for using this method would be helpful.

\textcolor{blue}{Very good point. We assumed that the distance decay function would be apparent from the reference to thresholds. We now note on \emph{page} that the distance decay is as follows:}

$$
\color{blue}{{w_{ij} = \begin{cases} 
      1 & \text{when } t_{ij}\leq \gamma \\
      0 & \text{otherwise} 
   \end{cases}}}
$$
\textcolor{blue}{where $\gamma$ is the threshold.}

\textcolor{blue}{With respect to the "counter-intuitive" result that accessibility declines when the distance threshold increases, we can illustrate the effect with a simple example. Imagine a station with a single bicycle. A single person is located at 3 minutes from that station. Then, a single person is located at 4 minutes from that station. Finally, a third person is located at 5 minutes from the station. Suppose that the catchment of the station extends to a threshold of three minutes. The population within the catchment is 1, and the level of service is therefore 1 bicycle per person. Since the other two people in this simple system do not reach the station within three minutes they are not serviced. Hence, the person at 3 minutes enjoys a high level of accesibility, since it can reach a level of service of 1 bicycle per person. Next, suppose that the catchment of the station is 4 minutes. Now two people are in the service area of the station. The level of service of the station is 1/2 bicycle per person. These two people now collectively have lower accessibility, since they can reach only a lower level of service. Finally, suppose that the catchment of the station includes all three people: the level of service now is 1/3 bicycle per person, and collectively the accessibility is even lower. Now, perhaps the confusion is about what accessibility means in this framework. As this simple example shows, it means accessibility to level of service. When the catchment area is small, few people enjoy relatively high levels of accessibility; when the catchment area is large, more people enjoy accessibility, but only to lower levels of service. We discuss the motivation for using this approach in our response to your first point. Geurs and van Wee (2004), as cited in the paper, note that land-use components of accessibility measures take congestion effects into account.}

4. Analysis shows that accessibility increase is modest especially for population in the bottom 20% of median total household income. How do you interpret this finding? Does that mean the equity stations fail their purposes?

\textcolor{blue}{Thank you for this question. In our view, the equity stations were a qualified success: they increased accessibility in general, and more people have higher accessibility than without the equity stations. This suggests that horizontal equity improved. As well, the accessibility differential for people in DAs with low incomes and people in DAs with higher incomes became smaller, but accessibility still was much lower for lower income populations even after the introduction of the equity stations. Hence, we believe that the gap in vertical equity was only modestly addressed. Please see the revised discussion.}

5. Eq. (4) and (5), I could not see the differences between the terms on the right hand side. If they are not same thing, why use two notation?

\textcolor{blue}{Thank you for pointing this out. There were typos in these formulas, and they should be as follows. In the first step:}
$$
\color{blue}{{w_{ij}^{i} = \frac {w_{ij}}{\sum_{j = 1}^{J} {w_{ij}}}}}
$$

\textcolor{blue}{and in the second step:}
$$
\color{blue}{{w_{ij}^{j} = \frac {w_{ij}}{\sum_{i = 1}^{n} {w_{ij}}}}}
$$

\textcolor{blue}{The difference is that in the first step the weights are row-standardized and in the second step they are column-standardized.}

\textcolor{blue}{Thank you again for the opportunity to clarify the above points.}

## Reviewer #2: 

The authors have addressed my concerns

\textcolor{blue}{Thank you again for your suggestions to improve the paper.}